using System;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using SMA.Helper;
using SMA.Models;
using SMA.Services;

namespace SMA.ViewModels.UserViewModels
{
    public class AddUserViewModel : INotifyPropertyChanged
    {
        private readonly Prn212G3Context _context;
        private readonly AuthService _authService;
        
        private string _autoGeneratedUserId;
        private string _userName;
        private string _email;
        private string _password;
        private string _confirmPassword;
        private string _phone;
        private string _address;
        private string _citizenId;
        private int _selectedGenderIndex;
        private int _selectedRoleIndex;
        private bool _isLoading;
        private string _errorMessage;
        private bool _isPasswordVisible;
        private bool _isConfirmPasswordVisible;

        // Properties
        public string AutoGeneratedUserId
        {
            get => _autoGeneratedUserId;
            set
            {
                _autoGeneratedUserId = value;
                OnPropertyChanged();
            }
        }

        public string UserName
        {
            get => _userName;
            set
            {
                _userName = value;
                OnPropertyChanged();
                ClearError();
            }
        }

        public string Email
        {
            get => _email;
            set
            {
                _email = value;
                OnPropertyChanged();
                ClearError();
            }
        }

        public string Password
        {
            get => _password;
            set
            {
                _password = value;
                OnPropertyChanged();
                ClearError();
            }
        }

        public string ConfirmPassword
        {
            get => _confirmPassword;
            set
            {
                _confirmPassword = value;
                OnPropertyChanged();
                ClearError();
            }
        }

        public string Phone
        {
            get => _phone;
            set
            {
                _phone = value;
                OnPropertyChanged();
            }
        }

        public string Address
        {
            get => _address;
            set
            {
                _address = value;
                OnPropertyChanged();
            }
        }

        public string CitizenId
        {
            get => _citizenId;
            set
            {
                _citizenId = value;
                OnPropertyChanged();
                ClearError();
            }
        }

        public int SelectedGenderIndex
        {
            get => _selectedGenderIndex;
            set
            {
                _selectedGenderIndex = value;
                OnPropertyChanged();
            }
        }

        public int SelectedRoleIndex
        {
            get => _selectedRoleIndex;
            set
            {
                _selectedRoleIndex = value;
                OnPropertyChanged();
                // Regenerate UserID when role changes
                GenerateUserId();
            }
        }

        public bool IsLoading
        {
            get => _isLoading;
            set
            {
                _isLoading = value;
                OnPropertyChanged();
            }
        }

        public string ErrorMessage
        {
            get => _errorMessage;
            set
            {
                _errorMessage = value;
                OnPropertyChanged();
            }
        }

        public bool IsPasswordVisible
        {
            get => _isPasswordVisible;
            set
            {
                _isPasswordVisible = value;
                OnPropertyChanged();
            }
        }

        public bool IsConfirmPasswordVisible
        {
            get => _isConfirmPasswordVisible;
            set
            {
                _isConfirmPasswordVisible = value;
                OnPropertyChanged();
            }
        }

        // Commands
        public ICommand CreateUserCommand { get; }
        public ICommand CancelCommand { get; }
        public ICommand TogglePasswordVisibilityCommand { get; }
        public ICommand ToggleConfirmPasswordVisibilityCommand { get; }

        public AddUserViewModel()
        {
            _context = new Prn212G3Context();
            _authService = new AuthService();

            _userName = string.Empty;
            _email = string.Empty;
            _password = string.Empty;
            _confirmPassword = string.Empty;
            _phone = string.Empty;
            _address = string.Empty;
            _citizenId = string.Empty;
            _selectedGenderIndex = 0; // Default: Male
            _selectedRoleIndex = 1; // Default: Staff
            _isLoading = false;
            _errorMessage = string.Empty;
            _isPasswordVisible = false;
            _isConfirmPasswordVisible = false;

            CreateUserCommand = new RelayCommand(ExecuteCreateUser, CanExecuteCreateUser);
            CancelCommand = new RelayCommand(ExecuteCancel);
            TogglePasswordVisibilityCommand = new RelayCommand(_ => TogglePasswordVisibility());
            ToggleConfirmPasswordVisibilityCommand = new RelayCommand(_ => ToggleConfirmPasswordVisibility());

            // Generate initial UserID
            GenerateUserId();
        }

        private void GenerateUserId()
        {
            try
            {
                // Determine prefix based on role
                string prefix = SelectedRoleIndex == 0 ? "A" : "S"; // 0=Admin, 1=Staff

                // Get all users with this prefix
                var existingUsers = _context.Users
                    .Where(u => u.UserId.StartsWith(prefix))
                    .Select(u => u.UserId)
                    .ToList();

                // Find next available number
                int maxNumber = 0;
                foreach (var userId in existingUsers)
                {
                    if (userId.Length >= 4) // Format: A001, S001
                    {
                        string numberPart = userId.Substring(1);
                        if (int.TryParse(numberPart, out int number))
                        {
                            if (number > maxNumber)
                            {
                                maxNumber = number;
                            }
                        }
                    }
                }

                // Generate next ID
                int nextNumber = maxNumber + 1;
                AutoGeneratedUserId = $"{prefix}{nextNumber:D3}"; // Format: A001, A002, S001, S002...
            }
            catch (Exception ex)
            {
                AutoGeneratedUserId = SelectedRoleIndex == 0 ? "A001" : "S001"; // Fallback
                System.Diagnostics.Debug.WriteLine($"Error generating UserId: {ex.Message}");
            }
        }

        private void TogglePasswordVisibility()
        {
            IsPasswordVisible = !IsPasswordVisible;
        }

        private void ToggleConfirmPasswordVisibility()
        {
            IsConfirmPasswordVisible = !IsConfirmPasswordVisible;
        }

        private bool CanExecuteCreateUser(object parameter)
        {
            return !IsLoading;
        }

        private void ExecuteCreateUser(object parameter)
        {
            ClearError();

            // Validate
            if (string.IsNullOrWhiteSpace(UserName))
            {
                ErrorMessage = "Username is required.";
                return;
            }

            if (string.IsNullOrWhiteSpace(Email))
            {
                ErrorMessage = "Email is required.";
                return;
            }

            if (!IsValidEmail(Email))
            {
                ErrorMessage = "Please enter a valid email address.";
                return;
            }

            // Check if Email already exists
            if (_context.Users.Any(u => u.Email == Email))
            {
                ErrorMessage = "This email is already registered. Please use a different email.";
                return;
            }

            if (string.IsNullOrWhiteSpace(Password))
            {
                ErrorMessage = "Password is required.";
                return;
            }

            if (Password.Length < 6)
            {
                ErrorMessage = "Password must be at least 6 characters long.";
                return;
            }

            if (Password != ConfirmPassword)
            {
                ErrorMessage = "Passwords do not match.";
                return;
            }

            if (string.IsNullOrWhiteSpace(CitizenId))
            {
                ErrorMessage = "Citizen ID is required.";
                return;
            }

            // Check if CitizenId already exists
            if (_context.Users.Any(u => u.CitizenId == CitizenId))
            {
                ErrorMessage = "Citizen ID already exists. Please use a different Citizen ID.";
                return;
            }

            IsLoading = true;

            try
            {
                // Regenerate UserID to ensure it's still unique
                GenerateUserId();

                // Double-check if generated ID exists (race condition safety)
                if (_context.Users.Any(u => u.UserId == AutoGeneratedUserId))
                {
                    ErrorMessage = "Generated User ID already exists. Please try again.";
                    return;
                }

                // Create new user
                var newUser = new User
                {
                    UserId = AutoGeneratedUserId,
                    UserName = UserName,
                    Email = Email,
                    Password = _authService.HashPassword(Password), // Hash password
                    Phone = Phone,
                    Address = Address,
                    CitizenId = CitizenId,
                    Gender = SelectedGenderIndex == 0 ? "Male" : "Female",
                    Role = SelectedRoleIndex == 0 ? "Admin" : "Staff",
                    Status = "Active", // Default status
                    HireDate = DateTime.Now,
                    Avatar = null,
                    PasswordRecoveryToken = null,
                    TokenExpiry = null
                };

                // Add to database
                _context.Users.Add(newUser);
                _context.SaveChanges();

                MessageBox.Show($"User '{UserName}' created successfully with ID: {AutoGeneratedUserId}", "Success",
                    MessageBoxButton.OK, MessageBoxImage.Information);

                // Close window
                CloseWindow(parameter);
            }
            catch (Exception ex)
            {
                ErrorMessage = $"Error creating user: {ex.Message}";
            }
            finally
            {
                IsLoading = false;
            }
        }

        private void ExecuteCancel(object parameter)
        {
            CloseWindow(parameter);
        }

        private void CloseWindow(object parameter)
        {
            if (parameter is Window win)
            {
                win.Close();
            }
        }

        private bool IsValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }
        }

        private void ClearError()
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ErrorMessage = string.Empty;
            }
        }

        // INotifyPropertyChanged Implementation
        public event PropertyChangedEventHandler? PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
